### ISSUE TITLE
关于 和目ax18 和 兆能m2 非常小非常小的小bug

### ISSUE THREAD

**Issue by qwerttvv** [VIKINGYFY/immortalwrt#14]
~~嗐，都不影响使用，但还是反馈一下子~~

~~我路由器ax18和m2一样一个~~

~~我只能保证ax18机器的主板100%是ax18，m2的主板不敢保证100%是m2~~

~~因为ax18是买的原封后来自己改1g，m2是买的二手1g（反正壳子是m2）~~

~~现在问题来了，之前一直是编译m2的固件两个一起刷的，看到源码今天ax18的有改动，心血来潮编译了一个ax18的固件给ax18机器刷了~~

~~反正目前 https://github.com/VIKINGYFY/immortalwrt/tree/9e1ab7aeb59db30f8160bc300331b87e0c95b788 的情况下，编译ax18的固件在ax18机器下led灯一个都不亮，m2机器未知（拿走了不在我家）~~

~~以前都是编译的m2的固件，并且源码是 https://github.com/VIKINGYFY/immortalwrt/tree/9e1ab7aeb59db30f8160bc300331b87e0c95b788 之前的版，在ax18的机器和m2的机器上，也没注意led亮的对不对，反正是有亮的……~~

~~还有一个就是ax18机器和m2机器的lan都是反的，机器是123，固件是321~~

编辑一下子

我眼拙……我爬上去看了，目前ax18机器刷了ax18的固件，确实亮了一个电源，wan不亮，但lan确实是反的哈哈

算了，不要在意这些没用的细节……

**Comment by VIKINGYFY** [comment]
lan口顺序和外壳标的不一样吗

**Comment by VIKINGYFY** [comment]
按照lede的改了一下，你明天再试试吧

**Comment by VIKINGYFY** [comment]
正则表达式把dts版本那一行也删掉了，刚修复了
