### ISSUE TITLE
UPnP不生效

### ISSUE THREAD

**Issue by zxc173123** [VIKINGYFY/immortalwrt#19]
不知道啥问题目前用下来就大雕的正常
![QQ截图20241121222140](https://github.com/user-attachments/assets/193f0c1f-59a5-4b67-a5d9-4faa1aaa0c66)
![QQ截图20241121222207](https://github.com/user-attachments/assets/e87b6423-7791-4e61-802e-1c931d4ba6f2)

**Comment by VIKINGYFY** [comment]
自行打补丁，或者更换打好补丁的UPNP
