### ISSUE TITLE
Aw1000的固件编译出来2.5g网口不能用

### ISSUE THREAD

**Issue by qwer155168** [VIKINGYFY/immortalwrt#21]
使用您的源码默认配置编译出来以后2.5g网口接口里是识别的，但是插上不亮灯也不能使用，使用上游immortalwrt的源码编译出来是正常的

**Comment by VIKINGYFY** [comment]
看了一下，dts文件仅添加了nss，其他未变动，具体没有设备测试

**Comment by qwer155168** [comment]
> 我参考了lede的修改，明天你再试试

好的，谢谢，我明天再编一个尝试一下
