### ISSUE TITLE
Since the new update, my build has been broken. JDC AX6600

### ISSUE THREAD

**Issue by Doanduy09** [VIKINGYFY/immortalwrt#22]
Since the new update, my build has been broken. I hope you can help me fix it. Thanks.
![image](https://github.com/user-attachments/assets/dda3f76f-47a5-4989-b5d2-fbd185a91175)

**Comment by VIKINGYFY** [comment]
please upload the complete log

**Comment by Doanduy09** [comment]
I have fully downloaded it, it happened when there was a new update

> please upload the complete log
