### ISSUE TITLE
最新的代码编译的固件，JDCloud AX1800 Pro 无法启动WIFI

### ISSUE THREAD

**Issue by wuruxu** [VIKINGYFY/immortalwrt#25]
一个礼拜前，是正常的
[001.log](https://github.com/user-attachments/files/17891374/001.log)

**Comment by VIKINGYFY** [comment]
尝试一下不保留配置刷机或者UB下重刷

**Comment by wuruxu** [comment]
我再试试

**Comment by wuruxu** [comment]
我通过ub 刷进去，也是不行的

**Comment by VIKINGYFY** [comment]
那就不太清楚了，我这边群里几个人都刷了，没问题

**Comment by wuruxu** [comment]
那我在这里再看看编译配置

**Comment by wuruxu** [comment]
现在可以了，我这里是选择了 Multi Device,  AX6600 和 AX1800 Pro ,  Firmware / ath10k Board-Specific Overrides / ipq-wifi-jdcloud_re-ss-01  我把这个从 M 改称 *   ，好像就正常了

**Comment by VIKINGYFY** [comment]
完全不熟menu
折腾好了就行

**Comment by wuruxu** [comment]
谢谢了
