### ISSUE TITLE
i got zyxel ex5700

### ISSUE THREAD

**Issue by Doanduy09** [VIKINGYFY/immortalwrt#27]
i got zyxel ex5700, can you support wifi driver mediatek. Thansks You.
https://git01.mediatek.com/plugins/gitiles/openwrt/feeds/mtk-openwrt-feeds/

**Comment by wuruxu** [comment]
This project code is only applicable to Qualcomm devices.

**Comment by VIKINGYFY** [comment]
21.02 CloseWRT project (mtk sdk and mac80211 interface)
https://github.com/hanwckf/immortalwrt-mt798x

firmware
https://github.com/VIKINGYFY/CloseWRT-CI

master OpenWRT project (mt76 driver and mac80211 interface)
https://github.com/immortalwrt/immortalwrt
