### ISSUE TITLE
Since the new update, my build has been broken. JDC AX6600

### ISSUE THREAD

**Issue by Doanduy09** [VIKINGYFY/immortalwrt#39]
Hi You !
Since the new update, my build has been broken. JDC AX6600

![image](https://github.com/user-attachments/assets/5c53dfad-3ce7-4985-8023-025a4e25a67f)

**Comment by VIKINGYFY** [comment]
Please check your build environment to make sure it is clean.

**Comment by Doanduy09** [comment]
> Please check your build environment to make sure it is clean.

Thasks....

**Comment by Doanduy09** [comment]
> Please check your build environment to make sure it is clean.

In this update, the wifi name and password cannot be changed.

**Comment by VIKINGYFY** [comment]
This is a BUG in upstream luci and has been fixed.
