### ISSUE TITLE
大佬，更新源码后编译的固件没有无线WIFI选项，手机也搜不到WIFI

### ISSUE THREAD

**Issue by mitsukileung** [VIKINGYFY/immortalwrt#43]
![屏幕截图 2024-12-30 113254](https://github.com/user-attachments/assets/c688b5cf-f8c9-4251-8243-783098045cfa)

ipq807x/Ax6

大佬，更新源码后编译的固件没有无线WIFI选项，手机也搜不到WIFI
下载大佬 https://github.com/VIKINGYFY/OpenWRT-CI/releases/tag/IPQ807X-WIFI-YES_immortalwrt.git-main_24.12.30_04.21.30 的固件也是一样

**Comment by VIKINGYFY** [comment]
目前正在排查

**Comment by VIKINGYFY** [comment]
现在应该是修好了，你再试试

**Comment by mitsukileung** [comment]
> 现在应该是修好了，你再试试

刚刚编译固件试了一下，无线正常了，多谢大佬！
